### ISSUE TITLE
FileNotFoundError ( 'oracleDir/zipr.map' )

### ISSUE THREAD

**Issue by kimiwanano** [FoRTE-Research/HeXcite#1]
I tried to test it with a simple example program. I directly completed the binary rewrite with zipr already packaged, and tried it on AFL, and it was already feasible. Next, I tried to test with HeXcite, and my steps were as follows:

`docker run -t -v /tmp:/io git.zephyr-software.com:4567/opensrc/zafl/zafl:latest /io/test /io/test_oracle.zafl -t ./oracleDir -f`
`docker run -t -v /tmp:/io git.zephyr-software.com:4567/opensrc/zafl/zafl:latest /io/test /io/test_oracle.zafl -t ./tracerDir/ -u`
![)N2M8M({ 76MHYK17 Q$@6T](https://user-images.githubusercontent.com/76025773/178236896-f9a876b7-68d4-48a2-8b0c-3a3ce31bf720.png)
![A9P$I$%3T(O$Y`FM24}0~LE](https://user-images.githubusercontent.com/76025773/178238520-f8473a32-38d5-4b93-a62b-ee151e6fda4b.png)

However, when I finished compiling, there was no required zipr.map in the corresponding folder, so I would like to ask whether oracleDir and tracerDir are folder setted by user, and why there is no zipr.map.

![DUZJFKUQQET })SCSG$9H~G](https://user-images.githubusercontent.com/76025773/178237070-62e3defc-1304-4f02-97bc-72a1bed61222.png)

**Comment by stevenagy** [comment]
Yeah, `oracleDir` and `tracerDir` are arguments that you need to pass in. Assuming `./oracleDir` and `./tracerDir` are accessible, I believe the `hexcite-mapper` command you want is as follows:
```./hexcite-mapper.py ./oracleDir ./tracerDir out.map map.log```

**Comment by kimiwanano** [comment]
It was an oversight. Sorry. But the same error was reported after I modified the command. zipr. map does not exist in oracleDir before executing hexcite-mapper.py, but it should be generated when filename_oracle.zafl is completed? However, I successfully generated filename_oracle.zafl but not zipr.map?

**Comment by stevenagy** [comment]
Can you zip up your output Zafl temp folder and attach it here?

**Comment by kimiwanano** [comment]
> Can you zip up your output Zafl temp folder and attach it here?

I ended up finding zipr.map (a path like this : `/data1/docker/overlay2/cc7f3edc648f84dd4498e07a97af3928f7d9ba6f8106c1046749d094ff310ce8/diff/tmp/tracerDir/zipr.map`) in the zafl execution container.  I implemented the instrumentation directly with the packaged container and was not familiar with the path rules, which caused these problems. Thank you for your patience!

But I have one more question. Currently HeXcite only supports Mach-O binaries?  Do not support ELF files？

![Q3_$G4O5(Z(AW}L6V)ZDM 2](https://user-images.githubusercontent.com/76025773/179230905-2413dcdd-7d77-4d5e-9376-2ecc6a773c67.png)

**Comment by stevenagy** [comment]
Sorry for the late reply! 

That check (and accompanying error message) looks like an artifact from AFL -- we don't do anything with Mach-O (yet ;)). I think doing `export AFL_SKIP_BIN_CHECK=1` should skip over that.

**Comment by kimiwanano** [comment]
> Sorry for the late reply!
> 
> That check (and accompanying error message) looks like an artifact from AFL -- we don't do anything with Mach-O (yet ;)). I think doing `export AFL_SKIP_BIN_CHECK=1` should skip over that.

Ok, now it's working. Thanks!

**Comment by stevenagy** [comment]
Glad to hear it!
